#!/bin/sh /etc/rc.common

START=95
STOP=10
USE_PROCD=1

PROG=/usr/sbin/mergen-watchdog
MERGEN_CONF=/etc/config/mergen

start_service() {
	local enabled
	config_load mergen
	config_get enabled global enabled '0'

	[ "$enabled" = "1" ] || return 0

	procd_open_instance mergen-watchdog
	procd_set_param command "$PROG"
	procd_set_param respawn 3600 5 5
	procd_set_param pidfile /var/run/mergen.pid
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

stop_service() {
	rm -f /var/lock/mergen.lock
	rm -f /var/run/mergen.pid
}

reload_service() {
	stop
	start
}

service_triggers() {
	procd_add_reload_trigger "mergen"
}
